#!/usr/bin/env bash
#Using a while loop with IFS to read the /etc/passwd file

while IFS=":" read -r username _x userid groupid info home shell
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $x, more info about the user here: $info"
done < /etc/passwd
