#!/usr/bin/env bash
# Using a while loop with IFS to read the /etc/passwd file

while IFS=: read -r username password uid gid gecos home shell

do
  echo "The user $username is part of the $gid gang,"
  echo "lives in $home and rides $shell."
  echo "User ID's place is protected by the passcode $password,"
  echo "more info about the user here: $gecos"

done < /etc/passwd
