#!/usr/bin/env bash
#writing a script that prints best school and hi on the last line

counter=0

while [ $counter -le 10 ]

do 
	if [ $counter -eq 9 ];
		then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	
	((counter))
done
