#!/usr/bin/env bash
#writing a script that print best school but print bad luck at 4th iteration and good luck on 8th iteration

counter=1

while [ $counter -le 10 ]

do
	if [ $counter -eq 4 ]; then

		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((counter++))
done
