#!/usr/bin/env bash
#writing bash script that displays the time for 12 hours and 59 minutes

hours=0

while [ $hours -le 12 ]

do
	minutes=0
	while [ $minutes -le 59 ]
	do
		echo "$hours:$minutes"
		((minutes++))
	done

	((hours++))
done
